### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/enumerables#1]
Please leave some comments.

**Comment by Kyle-Law** [comment]
Great job rebuilding enumearables @nyatindopatrick ! Here are some remarks from me:
- The project requires a different GitHub Branching. In this project, `development` branch should be created from `master` and set as default branch. (check the project spec for more details)

Aside from that, your codes look clean. Keep it up! 💯

**Comment by patriciachrysy** [comment]
Good job so far @nyatindopatrick, i will just have some few remarks:
- avoid using the for loop for your my_each, rubocop will ask you to change the for to each loop, but since you cannot use it, you'll have to change the loop
- Your my_count function does not work for Ranges, it raises an issue
- my_all?, my_any? and my_none are supposed to work both with block or parameter. You did not take the parameter case in consideration, check it out.
- I also agree with @Kyle-Law , you should implement the gitflow, otherwise, your repo will be marked invalid.
Keep up, you are almost there!

**Comment by nyatindopatrick** [comment]
Thank you for the comments.
